# ランダム推薦
0.5から5の一様乱数を予測評価値とする

In [2]:
# 親のフォルダのパスを追加
import sys; sys.path.insert(0, '..')
import importlib

from util.data_loader import DataLoader
from util.metric_calculator import MetricCalculator
# importlib.reload(util)

In [3]:
# Movielensのデータの読み込み
data_loader = DataLoader(num_users=1000, num_test_items=5, data_path='../data/ml-10M100K/')
movielens = data_loader.load()


   user_id  movie_id  rating   timestamp             title              genre  \
0        1       122     5.0   838985046  Boomerang (1992)  [Comedy, Romance]   
1      139       122     3.0   974302621  Boomerang (1992)  [Comedy, Romance]   
2      149       122     2.5  1112342322  Boomerang (1992)  [Comedy, Romance]   
3      182       122     3.0   943458784  Boomerang (1992)  [Comedy, Romance]   
4      215       122     4.5  1102493547  Boomerang (1992)  [Comedy, Romance]   

                                                 tag  
0  [dating, nudity (topless - brief), can't remem...  
1  [dating, nudity (topless - brief), can't remem...  
2  [dating, nudity (topless - brief), can't remem...  
3  [dating, nudity (topless - brief), can't remem...  
4  [dating, nudity (topless - brief), can't remem...  
   movie_id                               title  \
0         1                    Toy Story (1995)   
1         2                      Jumanji (1995)   
2         3             Grumpi

In [4]:
movielens.item_content.head()

movie_id                               title  \
0         1                    Toy Story (1995)   
1         2                      Jumanji (1995)   
2         3             Grumpier Old Men (1995)   
3         4            Waiting to Exhale (1995)   
4         5  Father of the Bride Part II (1995)   

                                               genre  \
0  [Adventure, Animation, Children, Comedy, Fantasy]   
1                     [Adventure, Children, Fantasy]   
2                                  [Comedy, Romance]   
3                           [Comedy, Drama, Romance]   
4                                           [Comedy]   

                                                 tag  
0  [pixar, pixar, pixar, animation, pixar, animat...  
1  [for children, game, animals, joe johnston, ro...  
2  [funniest movies, comedinha de velhinhos engra...  
3                                       [girl movie]  
4  [steve martin, pregnancy, remake, steve martin...

In [5]:
movielens.train.head()

user_id  movie_id  rating   timestamp             title              genre  \
1      139       122     3.0   974302621  Boomerang (1992)  [Comedy, Romance]   
2      149       122     2.5  1112342322  Boomerang (1992)  [Comedy, Romance]   
3      182       122     3.0   943458784  Boomerang (1992)  [Comedy, Romance]   
4      215       122     4.5  1102493547  Boomerang (1992)  [Comedy, Romance]   
6      281       122     3.0   844437024  Boomerang (1992)  [Comedy, Romance]   

                                                 tag  rating_order  
1  [dating, nudity (topless - brief), can't remem...         408.0  
2  [dating, nudity (topless - brief), can't remem...          84.0  
3  [dating, nudity (topless - brief), can't remem...        1104.0  
4  [dating, nudity (topless - brief), can't remem...         320.0  
6  [dating, nudity (topless - brief), can't remem...          42.0

In [6]:
# ランダムレコメンド
from src.random import RandomRecommender
recommender = RandomRecommender()
recommend_result = recommender.recommend(movielens)

In [7]:
len(recommend_result.rating)

5000

In [20]:
movielens.train.shape

(127830, 8)

In [21]:
movielens.train.head()

user_id  movie_id  rating   timestamp             title              genre  \
1      139       122     3.0   974302621  Boomerang (1992)  [Comedy, Romance]   
2      149       122     2.5  1112342322  Boomerang (1992)  [Comedy, Romance]   
3      182       122     3.0   943458784  Boomerang (1992)  [Comedy, Romance]   
4      215       122     4.5  1102493547  Boomerang (1992)  [Comedy, Romance]   
6      281       122     3.0   844437024  Boomerang (1992)  [Comedy, Romance]   

                                                 tag  rating_order  
1  [dating, nudity (topless - brief), can't remem...         408.0  
2  [dating, nudity (topless - brief), can't remem...          84.0  
3  [dating, nudity (topless - brief), can't remem...        1104.0  
4  [dating, nudity (topless - brief), can't remem...         320.0  
6  [dating, nudity (topless - brief), can't remem...          42.0

In [8]:
movielens.test.groupby("user_id").agg({"movie_id":len,"movie_id":list}) # 直近評価した5本の映画

movie_id
user_id                                 
1              [122, 362, 466, 520, 616]
2             [539, 151, 376, 719, 1391]
3        [3408, 5299, 5527, 7155, 33750]
4               [39, 266, 317, 432, 435]
5             [28, 926, 969, 1172, 1300]
...                                  ...
1048          [6, 741, 4878, 7361, 7160]
1050           [370, 466, 520, 145, 181]
1051          [858, 832, 852, 1566, 140]
1052      [3698, 6863, 3783, 5266, 5943]
1053       [457, 2028, 1242, 2501, 5418]

[1000 rows x 1 columns]

In [9]:
(movielens.test_user2items)

{1: [122, 362, 466, 520, 616],
 3: [3408, 5527],
 4: [266, 317],
 5: [926, 969, 1172, 1300],
 6: [1396, 1527, 1580, 2628],
 7: [5505, 1748, 2791, 6273],
 8: [3264],
 9: [50, 4226, 3429, 7361, 44761],
 10: [2194, 2917],
 11: [858, 2011, 2407, 2091],
 12: [3175],
 13: [1089, 2959, 1374],
 14: [2125],
 16: [1206],
 17: [2762, 3147, 1249],
 18: [6323, 924, 5785, 6707],
 19: [329],
 22: [539, 482],
 23: [367, 306, 223, 261, 319],
 24: [1393, 1047, 64],
 26: [733, 780, 587],
 27: [836],
 28: [1220, 2000, 2371, 2375],
 29: [3885],
 30: [1064, 1302, 1380],
 35: [1921, 2594, 3160, 3556],
 37: [541, 778, 1080],
 38: [48394, 54286],
 40: [457, 36, 3173, 1147],
 41: [1772, 2657],
 42: [1035, 1079, 1125, 1022],
 43: [1409, 1704, 1721, 1680],
 44: [1235, 1285, 3039, 1394, 3072],
 45: [1610, 866, 695],
 46: [1073, 1196, 7361],
 47: [1080, 1682, 2012, 2174, 2710],
 48: [4369, 55282, 59103],
 50: [151, 509],
 51: [2202, 4546, 6993],
 52: [2433],
 53: [3176, 2987, 3114, 3798],
 54: [277],
 55: [2140, 61

In [10]:
len(movielens.test.rating.tolist()) # 1000ユーザの5本の映画に対する評価

5000

In [55]:
from util.models import RecommendResult, Dataset
from src.base_recommender import BaseRecommender
from collections import defaultdict
import numpy as np

np.random.seed(0)


class RandomRecommender(BaseRecommender):
    def recommend(self, dataset: Dataset, **kwargs) -> RecommendResult:
        # ユーザーIDとアイテムIDに対して、０始まりのインデックスを割り振る
        unique_train_user_ids = sorted(dataset.train.user_id.unique())
        unique_train_movie_ids = sorted(dataset.train.movie_id.unique())
        train_user_id2index = dict(zip(unique_train_user_ids, range(len(unique_train_user_ids))))
        train_movie_id2index = dict(zip(unique_train_movie_ids, range(len(unique_train_movie_ids))))

        # ユーザー×アイテムの行列で、各セルの予測評価値は0.5〜5.0の一様乱数とする
        pred_matrix = np.random.uniform(0.5, 5.0, (len(unique_train_user_ids), len(unique_train_movie_ids)))

        print(len(unique_train_user_ids),len(unique_train_movie_ids),pred_matrix.shape) # ユーザ数, 1000ユーザが評価した

        # rmse評価用に、テストデータに出てくるユーザーとアイテムの予測評価値を格納する
        # イメージ: ユーザIDと映画の複合プライマリーキー.
        # 1000人いるユーザの5本分の評価を抽出しているので、5000
        rating_pred = []
        for i, row in dataset.test.iterrows():
            user_id = row["user_id"]
            # テストデータのアイテムIDが学習用に登場していない場合も乱数を格納する
            if row["movie_id"] not in train_movie_id2index:
                rating_pred.append(np.random.uniform(0.5, 5.0))
                continue
            # テストデータに現れるユーザーIDとアイテムIDのインデックスを取得し、評価値行列の値を取得する
            user_index = train_user_id2index[row["user_id"]]
            movie_index = train_movie_id2index[row["movie_id"]]
            pred_score = pred_matrix[user_index, movie_index]
            rating_pred.append(pred_score)
            # これ普通に rating_pred.append(np.random.uniform(0.5, 5.0)) で良いのでは？
        # movie_rating_predict["rating_pred"] = rating_pred

        # ランキング評価用のデータ作成
        # 各ユーザに対するおすすめ映画は、そのユーザがまだ評価していない映画の中からランダムに10作品とする
        # キーはユーザーIDで、バリューはおすすめのアイテムIDのリスト
        pred_user2items = defaultdict(list)
        # ユーザーがすでに評価した映画を取得する
        user_evaluated_movies = dataset.train.groupby("user_id").agg({"movie_id": list})["movie_id"].to_dict()
        for user_id in unique_train_user_ids:
            user_index = train_user_id2index[user_id]
            movie_indexes = np.argsort(-pred_matrix[user_index, :]) # ユーザごとに評価が高い順にしているっぽい？
            print(movie_indexes,len(movie_indexes))
            for movie_index in movie_indexes:
                movie_id = unique_train_movie_ids[movie_index]
                print(pred_matrix[user_index,movie_index])
                # テストデータを知らないのだから、訓練データからしか、推薦はできない。
                if movie_id not in user_evaluated_movies[user_id]:
                    pred_user2items[user_id].append(movie_id)
                if len(pred_user2items[user_id]) == 10:
                    break
        # movie_rating_predict = dataset.test.copy()
        # movie_rating_predict["rating_pred"] = rating_pred
        # rating_pred 
        return RecommendResult(rating_pred, pred_user2items)





## 雑にまとめ
### やっていることはめっちゃシンプル
- RecommendResultには:
    - テストデータ
        - 各ユーザが各映画にどのような評価値(0.5 ~ 5)を設定するか(rating_pred)
        - 訓練データの中でユーザが高い評価と設定する映画の上位10件はどれか？
    - を乱数により予測
 - 流れ:
    - 「各ユーザが各映画に0.5 ~ 5.0の間でどんな評価値を設定するかの予測値を格納する行列pred_matrics」（ユーザ数 * 映画数)を乱数値により、作成
    - 

In [56]:
recommender = RandomRecommender()
recommend_result = recommender.recommend(movielens)

1000 6673 (1000, 6673)
[2749 5081 2836 ... 1633 2055 3856] 6673
4.999838083441711
4.999804757409763
4.999770365967126
4.999690161584673
4.999138601526344
4.997652125448057
4.99675097264977
4.994811529555399
4.993369599687594
4.992596946946713
[1490 4373 1142 ... 1950 3964  975] 6673
4.999900783013253
4.999073859181644
4.99868770448717
4.997235123975559
4.996142027546048
4.995957994956379
4.995589378636319
4.994846767568644
4.994292248391959
4.9940765815052615
[1642 4371 2324 ... 5941 6121 1297] 6673
4.999829078035874
4.99916305893009
4.999106520649106
4.998751237525966
4.998130569801812
4.9941130590541825
4.992643518077586
4.991947828325541
4.991455152069977
4.990000894193131
[1256 3475 3858 ... 4515 4486 4157] 6673
4.999348743116861
4.99842913823981
4.998426616029457
4.997763506019286
4.997295498840121
4.997291372298218
4.997124818739914
4.996663964065347
4.9945258455195205
4.994371014009649
[5237  825 3467 ... 3736 1544 6297] 6673
4.999634350009521
4.999350319728306
4.999107155052953

In [57]:
#  評価
metric_calculator = MetricCalculator()
metrics = metric_calculator.calc(
    movielens.test.rating.tolist(), recommend_result.rating,
    movielens.test_user2items, recommend_result.user2items, k=10)
print(metrics)
# これらの評価指標が、どのくらいいけば、いい感じなんだろうか...。

rmse=1.883, Precision@K=0.000, Recall@K=0.001
